### ISSUE TITLE
Local Kind Cluster Improvements

### ISSUE THREAD

**Issue by cmwylie19** [rhobs/monitoring-stack-operator#128]
This is more of an enhancement request than a feature request related to the local kind cluster, and is just a suggestion that I think could improve the local experience and make it feel more realistic but I want to hear your thoughts.

When MSO is deployed, an alertmanager StatefulSet is created with 2 replicas.
```
k get po -n tenant-2
NAME                      READY   STATUS    RESTARTS   AGE
alertmanager-tenant-2-0   2/2     Running   0          4m16s
alertmanager-tenant-2-1   0/2     Pending   0          4m16s
```

The StatefulSet has podAntiAffinity to ensure the alertmanager pods go to different nodes.
```
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: alertmanager
                  app.kubernetes.io/part-of: tenant-2
              topologyKey: topology.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: alertmanager
                app.kubernetes.io/part-of: tenant-2
            topologyKey: kubernetes.io/hostname
```

**The problem**: Is that locally you will never have 2 nodes using the current kind configuration.
```
k get no 
NAME                 STATUS   ROLES                  AGE   VERSION
kind-control-plane   Ready    control-plane,master   16m   v1.22.4
```

To be able to fully see both replicas of the StatefulSet in action, you need 3 nodes (if you taint your control-plane).
- control-plane
- worker
- worker 

The `README.md` is very straight forward and has a very low barrier to entry, and I would want to keep it that way by still being able to spin up kind by copying and pasting just one block of code. Overvall, i believe  this would be a very useful part of the `README.md`, the e2e tests will still pass, and you have a environment that is ready for more advanced testing.
